name: benefits_dbt
version: 1.0.0
profile: benefits
require-dbt-version: ">=1.7.0,<2.0.0"

on-run-start: 
  - "{{ enforce_rls_on_marts() }}"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  benefits_dbt:
    +materialized: view
    postgres:
      +enabled: "{{ target.type == 'postgres' }}"
      staging:
        +materialized: view
        +schema: internal
      intermediate:
        +materialized: view
        +schema: internal
      marts:
        +materialized: table
    bigquery:
      +enabled: "{{ target.type == 'bigquery' }}"
      staging:
        +materialized: view
        +schema: internal
      intermediate:
        +materialized: view
        +schema: internal
      marts:
        +materialized: table