-- ## MANUAL UPDATE/REFRESH
-- ## Writes a table into materialized_views to translate partner codes into proper Partner Names
CREATE MATERIALIZED VIEW
data_referrer_codes AS

SELECT *
FROM (
    VALUES
    (null, 'No Partner'),
    ('', 'No Partner'),
    ('211co', '2-1-1 Colorado'),
    ('211nc', '2-1-1 North Carolina'),
    ('achs', 'Adams County Human Services'),
    ('achd', 'Adams County Health Department'),
    ('achdchw', 'Adams County Health Department - Community Health Workers'),
    ('achsshare', 'Adams County Human Services'),
    ('acph', 'Arapahoe County Public Health'),
    ('acphnlp', 'Arapahoe County Public Health'),
    ('ACTIONCenter', 'The Action Center'),
    ('adamscountyhealth', 'Adams County Health Department'),
    ('adelante', 'Adelante Community Development'),
    ('almosthome', 'Almost Home'),
    ('arapahoectypublichealth', 'Arapahoe County Public Health'),
    ('arapahoepublichealth', 'Arapahoe County Public Health'),
    ('back-to-school', 'Multiple Partners'),
    ('bayaud', 'Bayaud Enterprises'),
    ('bbt', 'Bright by Text'),
    ('bbttest', 'Other'),
    ('BGC', 'Boys & Girls Club of Metro Denver'),
    ('bgcmd', 'Boys & Girls Club of Metro Denver'),
    ('bia', 'Benefits in Action'),
    ('blueprint', 'Blueprint NC'),
    ('brightbytext', 'Bright by Text'),
    ('broomfield', 'City and County of Broomfield'),
    ('BWF-46951-TL', 'Builds with Families'),
    ('BWFProspective', 'Builds with Families'),
    ('BWFReferrals', 'Builds with Families'),
    ('careReach', 'Care Reach'),
    ('cch', 'Colorado Coalition for the Homeless'),
    ('ccig', 'Colorado Design Insight Group (CDIG)'),
    ('cdec', 'Colorado Department of Early Childhood (CDEC)'),
    ('cdecs', 'Colorado Department of Early Childhood (CDEC)'),
    ('cdig', 'Colorado Design Insight Group (CDIG)'),
    ('CEDP', 'Community Economic Defense Project'),
    ('cedp', 'Community Economic Defense Project'),
    ('childfirst', 'Child First'),
    ('cia', 'Community Investment Alliance'),
    ('CollegeView', 'College View High School'),
    ('coloradoparentcoalition', 'Colorado Statewide Parent Coalition'),
    ('community_investment_alliance', 'Community Investment Alliance'),
    ('denverhealth', 'Denver Health'),
    ('denverlibrary', 'Denver Public Library'),
    ('denverpubliclibrary', 'Denver Public Library'),
    ('dhs', 'Denver Human Services'),
    ('DPS', 'Denver Public Schools'),
    ('DPSCommunityHubs', 'Denver Public Schools'),
    ('DSST', 'Denver School of Science and Technology (DSST Public Schools)'),
    ('eaglecounty', 'Eagle County'),
    ('elRefugio', 'El Refugio'),
    ('email', 'Other'),
    ('energy_calculator', 'Other'),
    ('familyresourcecenter', 'Family Resource Center Association'),
    ('felp', 'Future Endeavors Life Program (FELP)'),
    ('fiel', 'Duke Project FIEL-NC (FIEL-NC)'),
    ('fircsummitresourcecenter', 'Summit County Resource Center (FIRC)'),
    ('flyers', 'Other'),
    ('Food', 'Community Food Access Program'),
    ('Food Access', 'Community Food Access Program'),
    ('frca', 'Family Resource Center Association'),
    ('fullcircle', 'Full Circle Leadville'),
    ('gac', 'Get Ahead Colorado'),
    ('getaheadtaxcalculator', 'Get Ahead Colorado'),
    ('hf', 'Hispanic Federation'),
    ('impactcharitable', 'Impact Charitable'),
    ('INSERTWHATEVERYOUWANTHERE', 'Other'),
    ('IRMP', 'Rocky Mountain Prep'),
    ('jeffcoHS', 'Jeffco Human Services'),
    ('jeffcoHSCM', 'Jeffco Human Services'),
    ('jeffcoPS', 'Jeffco Public Schools'),
    ('jfhs', 'Jeffco Human Services'),
    ('larimercounty', 'Larimer County'),
    ('lgs', 'Let''s Get Set'),
    ('mail', 'Other'),
    ('mcoa', 'Multidisciplinary Center on Aging'),
    ('mda', 'Montagnard Dega Association'),
    ('mgm', 'Mundeke Gospel Mission'),
    ('mountainProjects', 'Mountain Projects'),
    ('nc211', '2-1-1 North Carolina'),
    ('NCCHWA', 'NC Community Health Worker Association (NCCHWA)'),
    ('ncnc', 'NC Navigators Consortium'),
    ('nursefamilypartnership', 'Nurse-Family Partnership'),
    ('nw', 'Nariah''s Way'),
    ('onTrackFin', 'On Track Financial'),
    ('other', 'Other'),
    ('PBWF-TL-51601', 'Builds with Families'),
    ('pisgahLegal', 'Pisgah Legal Services'),
    ('pitkin', 'Pitkin County'),
    ('Project Worthmore', 'Project Worthmore'),
    ('pueblo', 'Pueblo County'),
    ('rcp', 'Refugee Community Partnership'),
    ('RMP', 'Rocky Mountain Prep'),
    ('rmp', 'Rocky Mountain Prep'),
    ('ruralHealthGroup', 'Rural Health Group'),
    ('salud', 'Salud Family Health Centers'),
    ('searchEngine', 'Other'),
    ('socialMedia', 'Other'),
    ('taxAssistanceSite', 'Other'),
    ('taxassistancesite', 'Other'),
    ('tellercounty', 'Teller County'),
    ('tepeyac', 'Tepeyac Health'),
    ('Tepeyac Health', 'Tepeyac Health'),
    ('TepeyacHealth', 'Tepeyac Health'),
    ('testOrProspect', 'Other'),
    ('TheGatheringPlace', 'The Gathering Place'),
    ('thegatheringplace', 'The Gathering Place'),
    ('unidxWNC', 'Unidx WNC'),
    ('villageExchange', 'Village Exchange'),
    ('waterstonechurch', 'Waterstone Church'),
    ('weAreDownHome', 'We Are Down Home'),
    ('wrcgso', 'Women''s Resource Center of Greensboro'),
    -- Could not match the following referrer codes to a partner:
    ('Sailthru', 'Other'),
    ('cgeneralprint', 'Other'),
    ('govdelivery', 'Other'),
    ('hello', 'Other'),
    ('hs_automation', 'Other'),
    ('neighbor', 'Other')

) AS data_referrer_codes (referrer_code, partner);
