{{
  config(
    materialized='table',
    post_hook="{{ setup_white_label_rls(this.name) }}",
    description='Materialized mart that unpivots benefit eligibility data into rows. Matches the trusted Terraform dashboard mapping for 100% parity.'
  )
}}

WITH base AS (
    SELECT
        white_label_id,
        partner,
        county,
        sum(CASE WHEN lifeline_annual > 0 THEN 1 ELSE 0 END) AS lifeline,
        sum(CASE WHEN snap_annual > 0 THEN 1 ELSE 0 END) AS snap,
        sum(CASE WHEN co_snap_annual > 0 THEN 1 ELSE 0 END) AS co_snap,
        sum(CASE WHEN nc_snap_annual > 0 THEN 1 ELSE 0 END) AS nc_snap,
        sum(CASE WHEN il_snap_annual > 0 THEN 1 ELSE 0 END) AS il_snap,
        sum(CASE WHEN ma_snap_annual > 0 THEN 1 ELSE 0 END) AS ma_snap,
        sum(CASE WHEN wic_annual > 0 THEN 1 ELSE 0 END) AS wic,
        sum(CASE WHEN co_wic_annual > 0 THEN 1 ELSE 0 END) AS co_wic,
        sum(CASE WHEN nc_wic_annual > 0 THEN 1 ELSE 0 END) AS nc_wic,
        sum(CASE WHEN il_wic_annual > 0 THEN 1 ELSE 0 END) AS il_wic,
        sum(CASE WHEN ma_wic_annual > 0 THEN 1 ELSE 0 END) AS ma_wic,
        sum(CASE WHEN tanf_annual > 0 THEN 1 ELSE 0 END) AS tanf,
        sum(CASE WHEN co_tanf_annual > 0 THEN 1 ELSE 0 END) AS co_tanf,
        sum(CASE WHEN nc_tanf_annual > 0 THEN 1 ELSE 0 END) AS nc_tanf,
        sum(CASE WHEN il_tanf_annual > 0 THEN 1 ELSE 0 END) AS il_tanf,
        sum(CASE WHEN ma_tafdc_annual > 0 THEN 1 ELSE 0 END) AS ma_tafdc,
        sum(CASE WHEN medicaid_annual > 0 THEN 1 ELSE 0 END) AS medicaid,
        sum(CASE WHEN co_medicaid_annual > 0 THEN 1 ELSE 0 END) AS co_medicaid,
        sum(CASE WHEN nc_medicaid_annual > 0 THEN 1 ELSE 0 END) AS nc_medicaid,
        sum(CASE WHEN il_medicaid_annual > 0 THEN 1 ELSE 0 END) AS il_medicaid,
        sum(CASE WHEN ma_mass_health_annual > 0 THEN 1 ELSE 0 END) AS ma_mass_health,
        sum(CASE WHEN ma_mass_health_limited_annual > 0 THEN 1 ELSE 0 END) AS ma_mass_health_limited,
        sum(CASE WHEN nc_emergency_medicaid_annual > 0 THEN 1 ELSE 0 END) AS nc_emergency_medicaid,
        sum(CASE WHEN emergency_medicaid_annual > 0 THEN 1 ELSE 0 END) AS emergency_medicaid,
        sum(CASE WHEN awd_medicaid_annual > 0 THEN 1 ELSE 0 END) AS awd_medicaid,
        sum(CASE WHEN cwd_medicaid_annual > 0 THEN 1 ELSE 0 END) AS cwd_medicaid,
        sum(CASE WHEN medicare_savings_annual > 0 THEN 1 ELSE 0 END) AS medicare_savings,
        sum(CASE WHEN nc_scca_annual > 0 THEN 1 ELSE 0 END) AS nc_scca,
        sum(CASE WHEN nc_lieap_annual > 0 THEN 1 ELSE 0 END) AS nc_lieap,
        sum(CASE WHEN nccip_annual > 0 THEN 1 ELSE 0 END) AS nccip,
        sum(CASE WHEN nc_aca_annual > 0 THEN 1 ELSE 0 END) AS nc_aca,
        sum(CASE WHEN ncwap_annual > 0 THEN 1 ELSE 0 END) AS nc_wap,
        sum(CASE WHEN ssi_annual > 0 THEN 1 ELSE 0 END) AS ssi,
        sum(CASE WHEN ssdi_annual > 0 THEN 1 ELSE 0 END) AS ssdi,
        sum(CASE WHEN nslp_annual > 0 THEN 1 ELSE 0 END) AS nslp,
        sum(CASE WHEN il_nslp_annual > 0 THEN 1 ELSE 0 END) AS il_nslp,
        sum(CASE WHEN eitc_annual > 0 THEN 1 ELSE 0 END) AS eitc,
        sum(CASE WHEN coeitc_annual > 0 THEN 1 ELSE 0 END) AS co_eitc,
        sum(CASE WHEN il_eitc_annual > 0 THEN 1 ELSE 0 END) AS il_eitc,
        sum(CASE WHEN ma_maeitc_annual > 0 THEN 1 ELSE 0 END) AS ma_eitc,
        sum(CASE WHEN ctc_annual > 0 THEN 1 ELSE 0 END) AS ctc,
        sum(CASE WHEN coctc_annual > 0 THEN 1 ELSE 0 END) AS co_ctc,
        sum(CASE WHEN il_ctc_annual > 0 THEN 1 ELSE 0 END) AS il_ctc,
        sum(CASE WHEN fatc_annual > 0 THEN 1 ELSE 0 END) AS fatc,
        sum(CASE WHEN shitc_annual > 0 THEN 1 ELSE 0 END) AS shitc,
        sum(CASE WHEN tabor_annual > 0 THEN 1 ELSE 0 END) AS tabor,
        sum(CASE WHEN oap_annual > 0 THEN 1 ELSE 0 END) AS oap,
        sum(CASE WHEN sunbucks_annual > 0 THEN 1 ELSE 0 END) AS sunbucks,
        sum(CASE WHEN leap_annual > 0 THEN 1 ELSE 0 END) AS leap,
        sum(CASE WHEN acp_annual > 0 THEN 1 ELSE 0 END) AS acp,
        sum(CASE WHEN ccap_annual > 0 THEN 1 ELSE 0 END) AS ccap,
        sum(CASE WHEN pell_grant_annual > 0 THEN 1 ELSE 0 END) AS pell_grant,
        sum(CASE WHEN erap_annual > 0 THEN 1 ELSE 0 END) AS erap,
        sum(CASE WHEN andcs_annual > 0 THEN 1 ELSE 0 END) AS andcs,
        sum(CASE WHEN bca_annual > 0 THEN 1 ELSE 0 END) AS bca,
        sum(CASE WHEN cdhcs_annual > 0 THEN 1 ELSE 0 END) AS cdhcs,
        sum(CASE WHEN cfhc_annual > 0 THEN 1 ELSE 0 END) AS cfhc,
        sum(CASE WHEN chp_annual > 0 THEN 1 ELSE 0 END) AS chp,
        sum(CASE WHEN co_head_start_annual > 0 THEN 1 ELSE 0 END) AS co_head_start,
        sum(CASE WHEN cocb_annual > 0 THEN 1 ELSE 0 END) AS co_cb,
        sum(CASE WHEN cowap_annual > 0 THEN 1 ELSE 0 END) AS co_wap,
        sum(CASE WHEN cpcr_annual > 0 THEN 1 ELSE 0 END) AS cpcr,
        sum(CASE WHEN dpp_annual > 0 THEN 1 ELSE 0 END) AS dpp,
        sum(CASE WHEN dptr_annual > 0 THEN 1 ELSE 0 END) AS dptr,
        sum(CASE WHEN dsr_annual > 0 THEN 1 ELSE 0 END) AS dsr,
        sum(CASE WHEN dtr_annual > 0 THEN 1 ELSE 0 END) AS dtr,
        sum(CASE WHEN ede_annual > 0 THEN 1 ELSE 0 END) AS ede,
        sum(CASE WHEN erc_annual > 0 THEN 1 ELSE 0 END) AS erc,
        sum(CASE WHEN fps_annual > 0 THEN 1 ELSE 0 END) AS fps,
        sum(CASE WHEN lwcr_annual > 0 THEN 1 ELSE 0 END) AS lwcr,
        sum(CASE WHEN ma_aca_annual > 0 THEN 1 ELSE 0 END) AS ma_aca,
        sum(CASE WHEN ma_ccdf_annual > 0 THEN 1 ELSE 0 END) AS ma_ccdf,
        sum(CASE WHEN ma_cfc_annual > 0 THEN 1 ELSE 0 END) AS ma_cfc,
        sum(CASE WHEN ma_eaedc_annual > 0 THEN 1 ELSE 0 END) AS ma_eaedc,
        sum(CASE WHEN ma_mbta_annual > 0 THEN 1 ELSE 0 END) AS ma_mbta,
        sum(CASE WHEN ma_ssp_annual > 0 THEN 1 ELSE 0 END) AS ma_ssp,
        sum(CASE WHEN mydenver_annual > 0 THEN 1 ELSE 0 END) AS mydenver,
        sum(CASE WHEN myspark_annual > 0 THEN 1 ELSE 0 END) AS myspark,
        sum(CASE WHEN nf_annual > 0 THEN 1 ELSE 0 END) AS nf,
        sum(CASE WHEN nfp_annual > 0 THEN 1 ELSE 0 END) AS nfp,
        sum(CASE WHEN omnisalud_annual > 0 THEN 1 ELSE 0 END) AS omnisalud,
        sum(CASE WHEN rag_annual > 0 THEN 1 ELSE 0 END) AS rag,
        sum(CASE WHEN rhc_annual > 0 THEN 1 ELSE 0 END) AS rhc,
        sum(CASE WHEN rtdlive_annual > 0 THEN 1 ELSE 0 END) AS rtdlive,
        sum(CASE WHEN trua_annual > 0 THEN 1 ELSE 0 END) AS trua,
        sum(CASE WHEN ubp_annual > 0 THEN 1 ELSE 0 END) AS ubp,
        sum(CASE WHEN upk_annual > 0 THEN 1 ELSE 0 END) AS upk,
        sum(CASE WHEN il_aabd_annual > 0 THEN 1 ELSE 0 END) AS il_aabd,
        sum(CASE WHEN il_aca_annual > 0 THEN 1 ELSE 0 END) AS il_aca,
        sum(CASE WHEN il_aca_adults_annual > 0 THEN 1 ELSE 0 END) AS il_aca_adults,
        sum(CASE WHEN il_all_kids_annual > 0 THEN 1 ELSE 0 END) AS il_all_kids,
        sum(CASE WHEN il_bap_annual > 0 THEN 1 ELSE 0 END) AS il_bap,
        sum(CASE WHEN il_family_care_annual > 0 THEN 1 ELSE 0 END) AS il_family_care,
        sum(CASE WHEN il_liheap_annual > 0 THEN 1 ELSE 0 END) AS il_liheap,
        sum(CASE WHEN il_moms_and_babies_annual > 0 THEN 1 ELSE 0 END) AS il_moms_and_babies,
        sum(CASE WHEN il_transit_reduced_fare_annual > 0 THEN 1 ELSE 0 END) AS il_transit_reduced_fare,
        sum(CASE WHEN cesn_bheap_annual > 0 THEN 1 ELSE 0 END) AS co_bheap,
        sum(CASE WHEN cesn_bhgap_annual > 0 THEN 1 ELSE 0 END) AS co_bhgap,
        sum(CASE WHEN cesn_care_annual > 0 THEN 1 ELSE 0 END) AS co_care,
        sum(CASE WHEN cesn_cngba_annual > 0 THEN 1 ELSE 0 END) AS co_cngba,
        sum(CASE WHEN cesn_cowap_annual > 0 THEN 1 ELSE 0 END) AS co_wap_energy,
        sum(CASE WHEN cesn_cpcr_annual > 0 THEN 1 ELSE 0 END) AS co_cpcr_energy,
        sum(CASE WHEN cesn_ea_annual > 0 THEN 1 ELSE 0 END) AS co_ea,
        sum(CASE WHEN cesn_energy_ebt_annual > 0 THEN 1 ELSE 0 END) AS co_energy_ebt,
        sum(CASE WHEN cesn_eoc_annual > 0 THEN 1 ELSE 0 END) AS co_eoc,
        sum(CASE WHEN cesn_eoccip_annual > 0 THEN 1 ELSE 0 END) AS co_eoccip,
        sum(CASE WHEN cesn_eocs_annual > 0 THEN 1 ELSE 0 END) AS co_eocs,
        sum(CASE WHEN cesn_leap_annual > 0 THEN 1 ELSE 0 END) AS co_leap_energy,
        sum(CASE WHEN cesn_poipp_annual > 0 THEN 1 ELSE 0 END) AS co_poipp,
        sum(CASE WHEN cesn_ubp_annual > 0 THEN 1 ELSE 0 END) AS co_ubp_energy,
        sum(CASE WHEN cesn_xceleap_annual > 0 THEN 1 ELSE 0 END) AS co_xceleap,
        sum(CASE WHEN cesn_xcelgap_annual > 0 THEN 1 ELSE 0 END) AS co_xcelgap
    FROM {{ ref('mart_screener_data') }}
    GROUP BY 1, 2, 3
)

SELECT
    t.benefit,
    t.count,
    b.white_label_id,
    b.partner,
    b.county
FROM base AS b
CROSS JOIN LATERAL unnest(
    ARRAY[
        'Lifeline',
        'SNAP',
        'CO SNAP',
        'NC SNAP',
        'IL SNAP',
        'MA SNAP',
        'WIC',
        'CO WIC',
        'NC WIC',
        'IL WIC',
        'MA WIC',
        'TANF',
        'CO TANF',
        'NC TANF',
        'IL TANF',
        'MA TAFDC',
        'Medicaid',
        'CO Medicaid',
        'NC Medicaid',
        'IL Medicaid',
        'MA Mass Health',
        'MA Mass Health Limited',
        'NC Emergency Medicaid',
        'Emergency Medicaid',
        'AWD Medicaid',
        'CWD Medicaid',
        'Medicare Savings',
        'NC SCCA',
        'NC LIEAP',
        'NCCIP',
        'NC ACA',
        'NC WAP',
        'SSI',
        'SSDI',
        'NSLP',
        'IL NSLP',
        'EITC',
        'CO EITC',
        'IL EITC',
        'MA EITC',
        'CTC',
        'CO CTC',
        'IL CTC',
        'FATC',
        'SHITC',
        'TABOR',
        'OAP',
        'Sunbucks',
        'LEAP',
        'ACP',
        'CCAP',
        'Pell Grant',
        'ERAP',
        'ANDCS',
        'BCA',
        'CDHCS',
        'CFHC',
        'CHP',
        'CO Head Start',
        'CO CB',
        'CO WAP',
        'CPCR',
        'DPP',
        'DPTR',
        'DSR',
        'DTR',
        'EDE',
        'ERC',
        'FPS',
        'LWCR',
        'MA ACA',
        'MA CCDF',
        'MA CFC',
        'MA EAEDC',
        'MA MBTA',
        'MA SSP',
        'My Denver',
        'My Spark',
        'NF',
        'NFP',
        'Omnisalud',
        'RAG',
        'RHC',
        'RTD Live',
        'TRUA',
        'UBP',
        'UPK',
        'IL AABD',
        'IL ACA',
        'IL ACA Adults',
        'IL All Kids',
        'IL BAP',
        'IL Family Care',
        'IL LIHEAP',
        'IL Moms and Babies',
        'IL Transit Reduced Fare',
        'CO BHEAP',
        'CO BHGAP',
        'CO CARE',
        'CO CNGBA',
        'CO WAP (Energy)',
        'CO CPCR (Energy)',
        'CO EA',
        'CO Energy EBT',
        'CO EOC',
        'CO EOCCIP',
        'CO EOCS',
        'CO LEAP (Energy)',
        'CO POIPP',
        'CO UBP (Energy)',
        'CO XCELEAP',
        'CO XCELGAP'
    ],
    ARRAY[
        b.lifeline,
        b.snap,
        b.co_snap,
        b.nc_snap,
        b.il_snap,
        b.ma_snap,
        b.wic,
        b.co_wic,
        b.nc_wic,
        b.il_wic,
        b.ma_wic,
        b.tanf,
        b.co_tanf,
        b.nc_tanf,
        b.il_tanf,
        b.ma_tafdc,
        b.medicaid,
        b.co_medicaid,
        b.nc_medicaid,
        b.il_medicaid,
        b.ma_mass_health,
        b.ma_mass_health_limited,
        b.nc_emergency_medicaid,
        b.emergency_medicaid,
        b.awd_medicaid,
        b.cwd_medicaid,
        b.medicare_savings,
        b.nc_scca,
        b.nc_lieap,
        b.nccip,
        b.nc_aca,
        b.nc_wap,
        b.ssi,
        b.ssdi,
        b.nslp,
        b.il_nslp,
        b.eitc,
        b.co_eitc,
        b.il_eitc,
        b.ma_eitc,
        b.ctc,
        b.co_ctc,
        b.il_ctc,
        b.fatc,
        b.shitc,
        b.tabor,
        b.oap,
        b.sunbucks,
        b.leap,
        b.acp,
        b.ccap,
        b.pell_grant,
        b.erap,
        b.andcs,
        b.bca,
        b.cdhcs,
        b.cfhc,
        b.chp,
        b.co_head_start,
        b.co_cb,
        b.co_wap,
        b.cpcr,
        b.dpp,
        b.dptr,
        b.dsr,
        b.dtr,
        b.ede,
        b.erc,
        b.fps,
        b.lwcr,
        b.ma_aca,
        b.ma_ccdf,
        b.ma_cfc,
        b.ma_eaedc,
        b.ma_mbta,
        b.ma_ssp,
        b.mydenver,
        b.myspark,
        b.nf,
        b.nfp,
        b.omnisalud,
        b.rag,
        b.rhc,
        b.rtdlive,
        b.trua,
        b.ubp,
        b.upk,
        b.il_aabd,
        b.il_aca,
        b.il_aca_adults,
        b.il_all_kids,
        b.il_bap,
        b.il_family_care,
        b.il_liheap,
        b.il_moms_and_babies,
        b.il_transit_reduced_fare,
        b.co_bheap,
        b.co_bhgap,
        b.co_care,
        b.co_cngba,
        b.co_wap_energy,
        b.co_cpcr_energy,
        b.co_ea,
        b.co_energy_ebt,
        b.co_eoc,
        b.co_eoccip,
        b.co_eocs,
        b.co_leap_energy,
        b.co_poipp,
        b.co_ubp_energy,
        b.co_xceleap,
        b.co_xcelgap
    ]
) AS t (benefit, count)
