{{
  config(
    materialized='view',
    description='Program eligibility aggregated by snapshot'
  )
}}

select
    eligibility_snapshot_id
    ,sum(case when name_abbreviated = 'acp' then estimated_value else 0 end) as acp_annual
    ,sum(case when name_abbreviated = 'andcs' then estimated_value ELSE 0 end) as andcs_annual
    ,sum(case when name_abbreviated = 'awd_medicaid' then estimated_value else 0 end) as awd_medicaid_annual
    ,sum(case when name_abbreviated = 'bca' then estimated_value else 0 end) as bca_annual
    ,sum(case when name_abbreviated = 'cccap' then estimated_value else 0 end) as cccap_annual
    ,sum(case when name_abbreviated = 'cdhcs' then estimated_value else 0 end) as cdhcs_annual
    ,sum(case when name_abbreviated = 'cfhc' then estimated_value else 0 end) as cfhc_annual
    ,sum(case when name_abbreviated = 'chp' then estimated_value else 0 end) as chp_annual
    ,sum(case when name_abbreviated = 'chs' then estimated_value else 0 end) as chs_annual
    ,sum(case when name_abbreviated = 'cocb' then estimated_value else 0 end) as cocb_annual
    ,sum(case when name_abbreviated = 'coctc' then estimated_value else 0 end) as coctc_annual
    ,sum(case when name_abbreviated = 'coeitc' then estimated_value else 0 end) as coeitc_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_bheap' then estimated_value else 0 end) as co_energy_calculator_bheap_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_bhgap' then estimated_value else 0 end) as co_energy_calculator_bhgap_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_care' then estimated_value else 0 end) as co_energy_calculator_care_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_cngba' then estimated_value else 0 end) as co_energy_calculator_cngba_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_cowap' then estimated_value else 0 end) as co_energy_calculator_cowap_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_cpcr' then estimated_value else 0 end) as co_energy_calculator_cpcr_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_ea' then estimated_value else 0 end) as co_energy_calculator_ea_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_energy_ebt' then estimated_value else 0 end) as co_energy_calculator_energy_ebt_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_eoc' then estimated_value else 0 end) as co_energy_calculator_eoc_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_eoccip' then estimated_value else 0 end) as co_energy_calculator_eoccip_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_eocs' then estimated_value else 0 end) as co_energy_calculator_eocs_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_leap' then estimated_value else 0 end) as co_energy_calculator_leap_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_poipp' then estimated_value else 0 end) as co_energy_calculator_poipp_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_ubp' then estimated_value else 0 end) as co_energy_calculator_ubp_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_xceleap' then estimated_value else 0 end) as co_energy_calculator_xceleap_annual
    ,sum(case when name_abbreviated = 'co_energy_calculator_xcelgap' then estimated_value else 0 end) as co_energy_calculator_xcelgap_annual
    ,sum(case when name_abbreviated = 'co_medicaid' then estimated_value else 0 end) as co_medicaid_annual
    ,sum(case when name_abbreviated = 'co_snap' then estimated_value else 0 end) as co_snap_annual
    ,sum(case when name_abbreviated = 'co_tanf' then estimated_value else 0 end) as co_tanf_annual
    ,sum(case when name_abbreviated = 'co_wic' then estimated_value else 0 end) as co_wic_annual
    ,sum(case when name_abbreviated = '_dev_ineligible' then estimated_value else 0 end) as _dev_ineligible_annual
    ,sum(case when name_abbreviated = 'cowap' then estimated_value else 0 end) as cowap_annual
    ,sum(case when name_abbreviated = 'cpcr' then estimated_value else 0 end) as cpcr_annual
    ,sum(case when name_abbreviated = 'ctc' then estimated_value else 0 end) as ctc_annual
    ,sum(case when name_abbreviated = 'cwd_medicaid' then estimated_value else 0 end) as cwd_medicaid_annual
    ,sum(case when name_abbreviated = 'dpp' then estimated_value else 0 end) as dpp_annual
    ,sum(case when name_abbreviated = 'dptr' then estimated_value else 0 end) as dptr_annual
    ,sum(case when name_abbreviated = 'dsr' then estimated_value else 0 end) as dsr_annual
    ,sum(case when name_abbreviated = 'dtr' then estimated_value else 0 end) as dtr_annual
    ,sum(case when name_abbreviated = 'ede' then estimated_value else 0 end) as ede_annual
    ,sum(case when name_abbreviated = 'eitc' then estimated_value else 0 end) as eitc_annual
    ,sum(case when name_abbreviated = 'emergency_medicaid' then estimated_value else 0 end) as emergency_medicaid_annual
    ,sum(case when name_abbreviated = 'erap' then estimated_value else 0 end) as erap_annual
    ,sum(case when name_abbreviated = 'erc' then estimated_value else 0 end) as erc_annual
    ,sum(case when name_abbreviated = 'fatc' then estimated_value else 0 end) as fatc_annual
    ,sum(case when name_abbreviated = 'fps' then estimated_value else 0 end) as fps_annual
    ,sum(case when name_abbreviated = 'leap' then estimated_value else 0 end) as leap_annual
    ,sum(case when name_abbreviated = 'lifeline' then estimated_value else 0 end) as lifeline_annual
    ,sum(case when name_abbreviated = 'lwcr' then estimated_value else 0 end) as lwcr_annual
    ,sum(case when name_abbreviated = 'ma_aca' then estimated_value else 0 end) as ma_aca_annual
    ,sum(case when name_abbreviated = 'ma_ccdf' then estimated_value else 0 end) as ma_ccdf_annual
    ,sum(case when name_abbreviated = 'ma_cfc' then estimated_value else 0 end) as ma_cfc_annual
    ,sum(case when name_abbreviated = 'ma_eaedc' then estimated_value else 0 end) as ma_eaedc_annual
    ,sum(case when name_abbreviated = 'ma_maeitc' then estimated_value else 0 end) as ma_maeitc_annual
    ,sum(case when name_abbreviated = 'ma_mass_health' then estimated_value else 0 end) as ma_mass_health_annual
    ,sum(case when name_abbreviated = 'ma_mass_health_limited' then estimated_value else 0 end) as ma_mass_health_limited_annual
    ,sum(case when name_abbreviated = 'ma_mbta' then estimated_value else 0 end) as ma_mbta_annual
    ,sum(case when name_abbreviated = 'ma_snap' then estimated_value else 0 end) as ma_snap_annual
    ,sum(case when name_abbreviated = 'ma_ssp' then estimated_value else 0 end) as ma_ssp_annual
    ,sum(case when name_abbreviated = 'ma_tafdc' then estimated_value else 0 end) as ma_tafdc_annual
    ,sum(case when name_abbreviated = 'ma_wic' then estimated_value else 0 end) as ma_wic_annual
    ,sum(case when name_abbreviated = 'medicaid' then estimated_value else 0 end) as medicaid_annual
    ,sum(case when name_abbreviated = 'medicare_savings' then estimated_value else 0 end) as medicare_savings_annual
    ,sum(case when name_abbreviated = 'mydenver' then estimated_value else 0 end) as mydenver_annual
    ,sum(case when name_abbreviated = 'myspark' then estimated_value else 0 end) as myspark_annual
    ,sum(case when name_abbreviated = 'nc_aca' then estimated_value else 0 end) as nc_aca_annual
    ,sum(case when name_abbreviated = 'nccip' then estimated_value else 0 end) as nccip_annual
    ,sum(case when name_abbreviated = 'nc_emergency_medicaid' then estimated_value else 0 end) as nc_emergency_medicaid_annual
    ,sum(case when name_abbreviated = 'nc_lieap' then estimated_value else 0 end) as nc_lieap_annual
    ,sum(case when name_abbreviated = 'nc_medicaid' then estimated_value else 0 end) as nc_medicaid_annual
    ,sum(case when name_abbreviated = 'nc_scca' then estimated_value else 0 end) as nc_scca_annual
    ,sum(case when name_abbreviated = 'nc_snap' then estimated_value else 0 end) as nc_snap_annual
    ,sum(case when name_abbreviated = 'nc_tanf' then estimated_value else 0 end) as nc_tanf_annual
    ,sum(case when name_abbreviated = 'ncwap' then estimated_value else 0 end) as ncwap_annual
    ,sum(case when name_abbreviated = 'nc_wic' then estimated_value else 0 end) as nc_wic_annual
    ,sum(case when name_abbreviated = 'il_aabd' then estimated_value else 0 end) as il_aabd_annual
    ,sum(case when name_abbreviated = 'il_aca' then estimated_value else 0 end) as il_aca_annual
    ,sum(case when name_abbreviated = 'il_aca_adults' then estimated_value else 0 end) as il_aca_adults_annual
    ,sum(case when name_abbreviated = 'il_all_kids' then estimated_value else 0 end) as il_all_kids_annual
    ,sum(case when name_abbreviated = 'il_bap' then estimated_value else 0 end) as il_bap_annual
    ,sum(case when name_abbreviated = 'il_ctc' then estimated_value else 0 end) as il_ctc_annual
    ,sum(case when name_abbreviated = 'il_eitc' then estimated_value else 0 end) as il_eitc_annual
    ,sum(case when name_abbreviated = 'il_family_care' then estimated_value else 0 end) as il_family_care_annual
    ,sum(case when name_abbreviated = 'il_liheap' then estimated_value else 0 end) as il_liheap_annual
    ,sum(case when name_abbreviated = 'il_medicaid' then estimated_value else 0 end) as il_medicaid_annual
    ,sum(case when name_abbreviated = 'il_moms_and_babies' then estimated_value else 0 end) as il_moms_and_babies_annual
    ,sum(case when name_abbreviated = 'il_nslp' then estimated_value else 0 end) as il_nslp_annual
    ,sum(case when name_abbreviated = 'il_snap' then estimated_value else 0 end) as il_snap_annual
    ,sum(case when name_abbreviated = 'il_tanf' then estimated_value else 0 end) as il_tanf_annual
    ,sum(case when name_abbreviated = 'il_transit_reduced_fare' then estimated_value else 0 end) as il_transit_reduced_fare_annual
    ,sum(case when name_abbreviated = 'il_wic' then estimated_value else 0 end) as il_wic_annual
    ,sum(case when name_abbreviated = 'nf' then estimated_value else 0 end) as nf_annual
    ,sum(case when name_abbreviated = 'nfp' then estimated_value else 0 end) as nfp_annual
    ,sum(case when name_abbreviated = 'nslp' then estimated_value else 0 end) as nslp_annual
    ,sum(case when name_abbreviated = 'oap' then estimated_value else 0 end) as oap_annual
    ,sum(case when name_abbreviated = 'omnisalud' then estimated_value else 0 end) as omnisalud_annual
    ,sum(case when name_abbreviated = 'pell_grant' then estimated_value else 0 end) as pell_grant_annual
    ,sum(case when name_abbreviated = 'rag' then estimated_value else 0 end) as rag_annual
    ,sum(case when name_abbreviated = 'rhc' then estimated_value else 0 end) as rhc_annual
    ,sum(case when name_abbreviated = 'rtdlive' then estimated_value else 0 end) as rtdlive_annual
    ,sum(case when name_abbreviated = 'shitc' then estimated_value else 0 end) as shitc_annual
    ,sum(case when name_abbreviated = 'sunbucks' then estimated_value else 0 end) as sunbucks_annual
    ,sum(case when name_abbreviated = 'snap' then estimated_value else 0 end) as snap_annual
    ,sum(case when name_abbreviated = 'ssdi' then estimated_value else 0 end) as ssdi_annual
    ,sum(case when name_abbreviated = 'ssi' then estimated_value else 0 end) as ssi_annual
    ,sum(case when name_abbreviated = 'tabor' then estimated_value else 0 end) as tabor_annual
    ,sum(case when name_abbreviated = 'tanf' then estimated_value else 0 end) as tanf_annual
    ,sum(case when name_abbreviated = 'trua' then estimated_value else 0 end) as trua_annual
    ,sum(case when name_abbreviated = 'ubp' then estimated_value else 0 end) as ubp_annual
    ,sum(case when name_abbreviated = 'upk' then estimated_value else 0 end) as upk_annual
    ,sum(case when name_abbreviated = 'wic' then estimated_value else 0 end) as wic_annual
from {{ source('django_apps', 'screener_programeligibilitysnapshot') }}
where eligible = true
group by eligibility_snapshot_id
